### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by selim1337** [whoisniskii/niskii.dev#3]
In the screenshot of the discord application I have shown below, there is an svg image next to the member since , if you can add it to the site, it would look cooler?

![image](https://user-images.githubusercontent.com/70216275/194774306-7e48c3f7-f27c-4247-8ed6-f467e21be912.png)

**Comment by davipatricio** [comment]
> In the screenshot of the discord application I have shown below, there is an svg image next to the member since , if you can add it to the site, it would look cooler?
> 
> ![image](https://user-images.githubusercontent.com/70216275/194774306-7e48c3f7-f27c-4247-8ed6-f467e21be912.png)

This icon actually only shows in guild profiles.

**Comment by selim1337** [comment]
Yes, you are right, What if the notes section is added?

![Ekran Alıntısı](https://user-images.githubusercontent.com/70216275/194840772-f5318908-74f2-4ca5-ae58-8e83ee51fee5.PNG)

**Comment by whoisniskii** [comment]
> ![Ekran Alıntısı](https://user-images.githubusercontent.com/70216275/194840772-f5318908-74f2-4ca5-ae58-8e83ee51fee5.PNG)

I don't intend to add this section for now, as I don't know what text to put in the notes 😅

**Comment by selim1337** [comment]
😅

**Comment by selim1337** [comment]
Are you considering adding the badges section?
I have some great ideas in my mind, but without your help it seems a little difficult for me to do 😅

![image](https://user-images.githubusercontent.com/70216275/195024208-2ae8bdcc-740e-4a02-8a85-7109bc8f1639.png)

**Comment by whoisniskii** [comment]
> Are you considering adding the badges section? I have some great ideas in my mind, but without your help it seems a little difficult for me to do 😅
> 
> ![image](https://user-images.githubusercontent.com/70216275/195024208-2ae8bdcc-740e-4a02-8a85-7109bc8f1639.png)

It's a good idea. I intend to add in the next commits

**Comment by selim1337** [comment]
> > Rozetler bölümünü eklemeyi düşünüyor musunuz? Aklımda bazı harika fikirler var, ama senin yardımın olmadan bunu yapmak benim için biraz zor görünüyor. 😅
> > ![resim](https://user-images.githubusercontent.com/70216275/195024208-2ae8bdcc-740e-4a02-8a85-7109bc8f1639.png)
> 
> Bu iyi bir fikir. Bir sonraki taahhütlere eklemek niyetindeyim

I take you as an example, you are a good developer Nicolas

**Comment by whoisniskii** [comment]
> I want to share another idea I have in mind with you, but it might be a little difficult. ![Example - 2](https://user-images.githubusercontent.com/70216275/195081581-aea8beb0-791b-420b-a4f1-62643cc823e0.PNG) ![image](https://user-images.githubusercontent.com/70216275/195081836-f47fd2e2-e6d7-4511-ae6f-6215f3a01496.png)
> 
> Do you think it's possible for a bubble to pop up when you click on the profile in this way and we can do the same in it as in discord?

It's possible, but I don't intend to add this because my site is almost done and I won't be messing with it anymore

**Comment by selim1337** [comment]
What do you plan to do after your site is finished I may have been a tight follower 😅
